### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by nebulous42069** [Zaxxon709/maxql#2]
Hey bud, sorry. I dont know where else to contact you, so I will ask here. Delete if necessary. I was wonderin if you would mind if I use your hchanger script for my own purpose in my build. I saw the switch logic you did and thought it was a great idea. Then ideas started popping up in my head on how I may be able to utilize this in my setup. I see for your use you have it switch the includes xml to change the home screen. Such an awesome idea btw. For my use would be similar. I was thinking of editing it a little so maybe it would switch my addon_data/skin.xxxx/settings.xml instead. I use a modded Xonfluence skin, so with that skin all the skin settings reside in the addon_data/skin.xxx/settings.xml. So I was thinking of making a few different settings.xml's this script could switch out, essentially changing the home screen of Xonfluence. (Xenon). Some ideas I had were Free, Debrid, Fen, Coalition, etc. Changing the widgets and menus to cater to different things I might come up with. Ive played around a little with it and came up with a custom dialog to insert the options, but before I get too far I just wanted to ask if it would be OK with you if I borrow the idea. Thanks bro!!

**Comment by Zaxxon709** [comment]
> Hey bud, sorry. I dont know where else to contact you, so I will ask here. Delete if necessary. I was wonderin if you would mind if I use your hchanger script for my own purpose in my build. I saw the switch logic you did and thought it was a great idea. Then ideas started popping up in my head on how I may be able to utilize this in my setup. I see for your use you have it switch the includes xml to change the home screen. Such an awesome idea btw. For my use would be similar. I was thinking of editing it a little so maybe it would switch my addon_data/skin.xxxx/settings.xml instead. I use a modded Xonfluence skin, so with that skin all the skin settings reside in the addon_data/skin.xxx/settings.xml. So I was thinking of making a few different settings.xml's this script could switch out, essentially changing the home screen of Xonfluence. (Xenon). Some ideas I had were Free, Debrid, Fen, Coalition, etc. Changing the widgets and menus to cater to different things I might come up with. Ive played around a little with it and came up with a custom dialog to insert the options, but before I get too far I just wanted to ask if it would be OK with you if I borrow the idea. Thanks bro!!

No problem, bud. You're welcome to use it. Look forward to seeing the results of what you have in mind. Cheers

**Comment by nebulous42069** [comment]
> > Hey bud, sorry. I dont know where else to contact you, so I will ask here. Delete if necessary. I was wonderin if you would mind if I use your hchanger script for my own purpose in my build. I saw the switch logic you did and thought it was a great idea. Then ideas started popping up in my head on how I may be able to utilize this in my setup. I see for your use you have it switch the includes xml to change the home screen. Such an awesome idea btw. For my use would be similar. I was thinking of editing it a little so maybe it would switch my addon_data/skin.xxxx/settings.xml instead. I use a modded Xonfluence skin, so with that skin all the skin settings reside in the addon_data/skin.xxx/settings.xml. So I was thinking of making a few different settings.xml's this script could switch out, essentially changing the home screen of Xonfluence. (Xenon). Some ideas I had were Free, Debrid, Fen, Coalition, etc. Changing the widgets and menus to cater to different things I might come up with. Ive played around a little with it and came up with a custom dialog to insert the options, but before I get too far I just wanted to ask if it would be OK with you if I borrow the idea. Thanks bro!!
> 
> No problem, bud. You're welcome to use it. Look forward to seeing the results of what you have in mind. Cheers

Thanks!!

**Comment by nebulous42069** [comment]
If you have time and are willing to give me a hand, can you just take a quick look at what I got and tell me what im doing wrong? Not getting any errors, but cant figure out why is not working. Tried various different ways, still does not seem to write the file. I would appreciate it if possible. Thank you.
[script.module.xenonplus.zip](https://github.com/Zaxxon709/maxql/files/13883062/script.module.xenonplus.zip)

**Comment by nebulous42069** [comment]
If you have time and are willing to give me a hand, can you just take a quick look at what I got and tell me what I might be doing wrong? Not getting any errors, but cant figure out why is not working. Tried various different ways, still does not seem to write the file. I would appreciate it if possible. Thank you.
[script.module.xenonplus.zip](https://github.com/Zaxxon709/maxql/files/13883100/script.module.xenonplus.zip)

**Comment by Zaxxon709** [comment]
> If you have time and are willing to give me a hand, can you just take a quick look at what I got and tell me what I might be doing wrong? Not getting any errors, but cant figure out why is not working. Tried various different ways, still does not seem to write the file. I would appreciate it if possible. Thank you. [script.module.xenonplus.zip](https://github.com/Zaxxon709/maxql/files/13883100/script.module.xenonplus.zip)

I don't think switching out the settings.xml is gonna work. The problem is Kodi loads this file on boot and it must be stored in memory. I remember using this skin and i would always edit with Kodi closed. If you edit with Kodi running and then exit Kodi the previous settings are saved instead of your edits. Unfortunately, i don't have anymore time to look at it this morning. Let me think about it today. I'll send you a msg on Telegram later. We can continue the conversation there and I can delete this Github issue. Thanks

**Comment by nebulous42069** [comment]
> > If you have time and are willing to give me a hand, can you just take a quick look at what I got and tell me what I might be doing wrong? Not getting any errors, but cant figure out why is not working. Tried various different ways, still does not seem to write the file. I would appreciate it if possible. Thank you. [script.module.xenonplus.zip](https://github.com/Zaxxon709/maxql/files/13883100/script.module.xenonplus.zip)
> 
> I don't think switching out the settings.xml is gonna work. The problem is Kodi loads this file on boot and it must be stored in memory. I remember using this skin and i would always edit with Kodi closed. If you edit with Kodi running and then exit Kodi the previous settings are saved instead of your edits. Unfortunately, i don't have anymore time to look at it this morning. Let me think about it today. I'll send you a msg on Telegram later. We can continue the conversation there and I can delete this Github issue. Thanks

Yea, thats what it looks like to me and I knew that before going in, lol. Just got excited and didnt think, lol.  I was trying to figure out where the heck Kodi caches the entire settings.xml with no luck. Did a NP++ search for a line in the settings.xml, and couldnt find a match anywhere in Kodi or windows/Programs/Kodi, so it must store the cache somewhere in the OS. But cool, delete this and ill talk to you later!!
